server:
  port: 7002

eureka:
  instace:
    #hostname: localhost # eureka服务端的实例名称(单机版配置)
    hostname: eureka7002.com # eureka服务端的实例名称(集群版配置)
  client:
    register-with-eureka: false # false表示不向注册中心注册自己
    fetch-registry: false # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url: 
      # defaultZone: http://${eureka.instace.hostname}:${server.port}/eureka/ # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址(单机版配置)
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/ # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址(集群版配置)
#  server: 
#    enable-self-preservation: false # 禁用自我保护模式(不推荐禁用)